//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CCSEntities : DbContext
    {
        public CCSEntities()
            : base("name=CCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CS_ACTIONLOG> CS_ACTIONLOG { get; set; }
        public virtual DbSet<CS_CODL> CS_CODL { get; set; }
        public virtual DbSet<CS_COMT> CS_COMT { get; set; }
        public virtual DbSet<CS_SYSEXCEPTION> CS_SYSEXCEPTION { get; set; }
        public virtual DbSet<CS_SYSLOG> CS_SYSLOG { get; set; }
        public virtual DbSet<CS_SYSMODULE> CS_SYSMODULE { get; set; }
        public virtual DbSet<CS_SYSMODULEOPERATE> CS_SYSMODULEOPERATE { get; set; }
        public virtual DbSet<CS_SYSRIGHT> CS_SYSRIGHT { get; set; }
        public virtual DbSet<CS_SYSRIGHTOPERATE> CS_SYSRIGHTOPERATE { get; set; }
        public virtual DbSet<CS_SYSROLE> CS_SYSROLE { get; set; }
        public virtual DbSet<CS_SYSUSER> CS_SYSUSER { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<VENDOR> VENDOR { get; set; }
    
        public virtual int SP_SYS_ClearUnusedRIGHTOPERATE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SYS_ClearUnusedRIGHTOPERATE");
        }
    
        public virtual ObjectResult<SP_SYS_GetRightOperate_Result> SP_SYS_GetRightOperate(string userId, string url)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SYS_GetRightOperate_Result>("SP_SYS_GetRightOperate", userIdParameter, urlParameter);
        }
    
        public virtual int SP_SYS_InsertSysRIGHT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SYS_InsertSysRIGHT");
        }
    }
}
