//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_CODL
    {
        public string VCH_NO { get; set; }
        public int VCH_SR { get; set; }
        public string ITEM_NO { get; set; }
        public string CS_ITEM_NO { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> A_QTY { get; set; }
        public Nullable<decimal> RCV_QTY { get; set; }
        public Nullable<decimal> RTN_QTY { get; set; }
        public Nullable<decimal> FREE_QTY { get; set; }
        public Nullable<decimal> FREC_QTY { get; set; }
        public Nullable<decimal> PRC { get; set; }
        public Nullable<decimal> AMT { get; set; }
        public Nullable<System.DateTime> PRCV_DT { get; set; }
        public string CO_WAHO_NO { get; set; }
        public string SVCH_TY { get; set; }
        public string SVCH_NO { get; set; }
        public Nullable<int> SVCH_SR { get; set; }
        public string PRJ_NO { get; set; }
        public string C_OUT { get; set; }
        public Nullable<decimal> OUT_RT { get; set; }
        public string C_CLS { get; set; }
        public string REMK { get; set; }
        public string CUS_FLD1 { get; set; }
        public string CUS_FLD2 { get; set; }
        public string CUS_FLD3 { get; set; }
        public string CUS_FLD4 { get; set; }
        public string CUS_FLD5 { get; set; }
        public string CUS_FLD6 { get; set; }
        public Nullable<decimal> TQA_MM { get; set; }
        public Nullable<decimal> PQA_MM { get; set; }
        public string CS_NO { get; set; }
        public string C_CFM { get; set; }
        public string MKT_CODE { get; set; }
        public Nullable<System.DateTime> PDT_DT { get; set; }
        public string PDT_WAHO_NO { get; set; }
        public string PDT_ITEM_NO { get; set; }
    }
}
