//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_MOMT
    {
        public string Id { get; set; }
        public string VCH_NO { get; set; }
        public System.DateTime VCH_DT { get; set; }
        public string FA_NO { get; set; }
        public string EMP_NO { get; set; }
        public string EMP_NM { get; set; }
        public string ITEM_NO { get; set; }
        public string IMG_NO { get; set; }
        public Nullable<System.DateTime> PLAN_BDT { get; set; }
        public Nullable<System.DateTime> PLAN_EDT { get; set; }
        public Nullable<int> PLAN_QTY { get; set; }
        public string CO_NO { get; set; }
        public Nullable<int> CO_SR { get; set; }
        public string HEAD_MARK { get; set; }
        public string RAWMTRL { get; set; }
        public Nullable<decimal> DIAMETER { get; set; }
        public string PLATING { get; set; }
        public string PRCS_NO { get; set; }
        public string REMK { get; set; }
        public string EXC_INSDBID { get; set; }
        public Nullable<System.DateTime> EXC_INSDATE { get; set; }
        public string EXC_UPDDBID { get; set; }
        public Nullable<System.DateTime> EXC_UPDDATE { get; set; }
        public string EXC_SYSOWNR { get; set; }
        public string EXC_ISLOCKED { get; set; }
        public string EXC_COMPANY { get; set; }
        public string HEAT_NO { get; set; }
    }
}
