//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_SEQ_NO
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
        public string PREFIX { get; set; }
        public string CODEFORMAT { get; set; }
        public Nullable<int> NO_LENGTH { get; set; }
        public Nullable<int> CURRENT_NO { get; set; }
        public string CURRENT_ORDNO { get; set; }
        public string STATUS { get; set; }
        public string ORGANIZATION { get; set; }
        public string EXC_INSDBID { get; set; }
        public Nullable<System.DateTime> EXC_INSDATE { get; set; }
        public string EXC_UPDDBID { get; set; }
        public Nullable<System.DateTime> EXC_UPDDATE { get; set; }
        public string EXC_SYSOWNR { get; set; }
        public string EXC_ISLOCKED { get; set; }
        public string EXC_COMPANY { get; set; }
    }
}
