//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_SYSRIGHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_SYSRIGHT()
        {
            this.CS_SYSRIGHTOPERATE = new HashSet<CS_SYSRIGHTOPERATE>();
        }
    
        public string Id { get; set; }
        public string ModuleId { get; set; }
        public string RoleId { get; set; }
        public bool Rightflag { get; set; }
    
        public virtual CS_SYSMODULE CS_SYSMODULE { get; set; }
        public virtual CS_SYSROLE CS_SYSROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_SYSRIGHTOPERATE> CS_SYSRIGHTOPERATE { get; set; }
    }
}
