//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_SYSUSER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CS_SYSUSER()
        {
            this.CS_SYSROLE = new HashSet<CS_SYSROLE>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string TrueName { get; set; }
        public string Card { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string QQ { get; set; }
        public string EmailAddress { get; set; }
        public string OtherContact { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Village { get; set; }
        public string Address { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Marital { get; set; }
        public string Political { get; set; }
        public string Nationality { get; set; }
        public string Native { get; set; }
        public string School { get; set; }
        public string Professional { get; set; }
        public string Degree { get; set; }
        public string DepId { get; set; }
        public string PosId { get; set; }
        public string Expertise { get; set; }
        public string JobState { get; set; }
        public string Photo { get; set; }
        public string Attach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CS_SYSROLE> CS_SYSROLE { get; set; }
    }
}
