//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CS_WIRES
    {
        public string Id { get; set; }
        public string WIRE_ID { get; set; }
        public System.DateTime STOCK_DATE { get; set; }
        public string RAWMTRL { get; set; }
        public decimal DIAMETER { get; set; }
        public Nullable<decimal> ORG_DIAMETER { get; set; }
        public string HEAT_NO { get; set; }
        public int WEIGHT { get; set; }
        public Nullable<int> STAND_WEIGTH { get; set; }
        public bool ANNEAL { get; set; }
        public string MARK { get; set; }
        public string MARK_NM { get; set; }
        public string PROCESS_FACTORY { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string TYPE_NM { get; set; }
        public string REMARK { get; set; }
        public string EXC_INSDBID { get; set; }
        public Nullable<System.DateTime> EXC_INSDATE { get; set; }
        public string EXC_UPDDBID { get; set; }
        public Nullable<System.DateTime> EXC_UPDDATE { get; set; }
        public string EXC_SYSOWNR { get; set; }
        public string EXC_ISLOCKED { get; set; }
        public string EXC_COMPANY { get; set; }
        public string CS_WIRE_ID { get; set; }
    }
}
