//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCY
    {
        public string CURRENCY1 { get; set; }
        public string CURR_NM { get; set; }
        public string CURR_NM_E { get; set; }
        public Nullable<decimal> EXCH_RATE { get; set; }
        public Nullable<int> ROUND_PRC { get; set; }
        public Nullable<int> ROUND_AMT_MT { get; set; }
        public Nullable<int> ROUND_AMT_DL { get; set; }
    }
}
