//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string EMP_NO { get; set; }
        public string EMP_NM { get; set; }
        public string ENG_NM { get; set; }
        public string C_STA { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BRD_DT { get; set; }
        public string EDU_NO { get; set; }
        public string SCH_NO { get; set; }
        public string MJR_NO { get; set; }
        public string RGS { get; set; }
        public string ID_NO { get; set; }
        public string MRD { get; set; }
        public string BLOOD { get; set; }
        public string ADDR_RGS { get; set; }
        public string ZNO_RGS { get; set; }
        public string ADDR_MAL { get; set; }
        public string ZNO_MAL { get; set; }
        public string CONTACTER { get; set; }
        public string TEL_NO { get; set; }
        public string TEL_NO2 { get; set; }
        public string TEL_NO3 { get; set; }
        public string E_MAIL { get; set; }
        public string FA_NO { get; set; }
        public string DEPM_NO { get; set; }
        public string JOB_NO { get; set; }
        public string JOB_RK { get; set; }
        public string ACT_NO { get; set; }
        public System.DateTime ARV_DT { get; set; }
        public Nullable<System.DateTime> LEV_DT { get; set; }
        public Nullable<System.DateTime> SPS_DT { get; set; }
        public Nullable<System.DateTime> RSU_DT { get; set; }
        public Nullable<System.DateTime> CHK_DT { get; set; }
        public Nullable<System.DateTime> ETR_DT { get; set; }
        public Nullable<System.DateTime> RTN_DT { get; set; }
        public Nullable<System.DateTime> DUE_DT { get; set; }
        public Nullable<System.DateTime> WYR_DT { get; set; }
        public string DOC_NO { get; set; }
        public string REMK { get; set; }
        public string BANK_NO { get; set; }
        public string ACC_NO { get; set; }
        public string BANK2_NO { get; set; }
        public string ACC2_NO { get; set; }
        public string BANK3_NO { get; set; }
        public string ACC3_NO { get; set; }
        public string C_TAX { get; set; }
        public Nullable<decimal> FIX_TAX { get; set; }
        public Nullable<decimal> FIX_RT { get; set; }
        public string C_OVT { get; set; }
        public Nullable<decimal> OVT_RT { get; set; }
        public string SFT_NO { get; set; }
        public string C_TKT { get; set; }
        public string TKT_NO { get; set; }
        public string IID_NO { get; set; }
        public string SSD_NO { get; set; }
        public Nullable<int> BRG_MS { get; set; }
        public Nullable<decimal> BAS_SLY { get; set; }
        public Nullable<decimal> ALP_RWD { get; set; }
        public string C_SAL_TY { get; set; }
        public string C_SAL_TM { get; set; }
        public string C_LPS_TY { get; set; }
        public Nullable<decimal> CP_LPS_EXP { get; set; }
        public Nullable<decimal> LPS_EXP { get; set; }
        public string RELA { get; set; }
        public byte[] IMG_GRP { get; set; }
    }
}
