//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPNO
    {
        public string EMP_NO { get; set; }
        public string EMP_NM { get; set; }
        public string DEPM_NO { get; set; }
        public string TEL_NO { get; set; }
        public string TEL_NO2 { get; set; }
        public string E_MAIL { get; set; }
        public string C_INV { get; set; }
        public string C_PUR { get; set; }
        public string C_COP { get; set; }
        public string C_PPS { get; set; }
        public string C_AST { get; set; }
        public string C_ACT { get; set; }
        public string C_SFC { get; set; }
        public string C_QMS { get; set; }
        public string C_BOM { get; set; }
        public string C_MOC { get; set; }
    }
}
